# Generated by Django 5.0.6 on 2024-07-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_published_date',
            field=models.DateTimeField(auto_now_add=True, db_column='blog_published_Date', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='filename',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
